### ISSUE TITLE
Checksum failures

### ISSUE THREAD

**Issue by QuorumMikeEdmans** [karo-electronics/karo-bsp#1]
I have been attempting to compile the rocko yocto build for the TX6UL. Each time I encounter checksum errors ( see below). How can I resolve these errors?

ERROR: libarchive-native-3.2.2-r0 do_fetch: Checksum failure fetching http://libarchive.org/downloads/libarchive-3.2.2.tar.gz
ERROR: libarchive-native-3.2.2-r0 do_fetch: Fetcher failure for URL: 'http://libarchive.org/downloads/libarchive-3.2.2.tar.gz'. Checksum mismatch!
File: '/home/mike/bitbake/rocko/TX6UL_first/downloads/libarchive-3.2.2.tar.gz' has md5 checksum 3be6f6fadbe8d884d37389bf8739e61f when 1ec00b7dcaf969dd2a5712f85f23c764 was expected
File: '/home/mike/bitbake/rocko/TX6UL_first/downloads/libarchive-3.2.2.tar.gz' has sha256 checksum 839937f7f2137871102115561f974f6f6dc0b6b4c437982575b016cf6a7bd94f when 691c194ee132d1f0f7a42541f091db811bc2e56f7107e9121be2bc8c04f1060f was expected
If this change is expected (e.g. you have upgraded to a new version without updating the checksums) then you can use these lines within the recipe:
SRC_URI[md5sum] = "3be6f6fadbe8d884d37389bf8739e61f"
SRC_URI[sha256sum] = "839937f7f2137871102115561f974f6f6dc0b6b4c437982575b016cf6a7bd94f"
Otherwise you should retry the download and/or check with upstream to determine if the file has become corrupted or otherwise unexpectedly modified.

ERROR: libarchive-native-3.2.2-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/mike/bitbake/rocko/TX6UL_first/tmp/work/x86_64-linux/libarchive-native/3.2.2-r0/temp/log.do_fetch.4628
ERROR: Task (virtual:native:/home/mike/bitbake/rocko/sources/poky/meta/recipes-extended/libarchive/libarchive_3.2.2.bb:do_fetch) failed with exit code '1'

**Comment by oliverwendt** [comment]
This is, as can be seen in the pasted message, a file for package downloaded directly by the Yocto framework.

If the URL - as given in the same message - would have been used to download the package's file manually and a (also manual) `md5sum`/`sha256sum` would have been done, as the package does and also gives as an output:

```
md5 checksum 3be6f6fadbe8d884d37389bf8739e61f when 1ec00b7dcaf969dd2a5712f85f23c764 was expected
```
on the downloaded file, it could have been seen that the file actually got the expected checksum. And hence:

Either you have a defective filesystem, HDD/SSD, or - may be interrupted download? - otherwise the file got corrupted.

Therefore there are three major solutions:
- Delete the file from the cache

- Clean your Yocto's cache, via bitbake command.
 [Welcome](https://github.com/karo-electronics/welcome#what-sources) -> Yocto -> Getting Started
There you'll find under 'References' to multiple bitbake cheat sheets

- Do a fschk on the pertinent FS
