### ISSUE TITLE
Checksum failures

### ISSUE THREAD

**Issue by QuorumMikeEdmans** [karo-electronics/karo-bsp#2]
So I have tried all the things you suggested:

- delete the file
- clean the cache

I also repeated the procedure on a different machine. Still the same thing. When I try to download the file (see link below) using a browser, the file download fails right at the end - giving "server problem" as the issue. Are you sure there is not a problem with the download repository?

http://libarchive.org/downloads/libarchive-3.2.2.tar.gz

**Comment by QuorumMikeEdmans** [comment]
I tried manually downloading the file using wget. The checksums are different from the expected. What am I doing wrong?

**Comment by oliverwendt** [comment]
Well just tried it **again** and I can **not** confirm your problem. See hereafter my CnP from my terminal:

(first one I downloaded with my desktop's browser, that why it's under "Downloads")
```
$ md5sum Downloads/libarchive-3.2.2\ \(1\).tar.gz 
1ec00b7dcaf969dd2a5712f85f23c764  Downloads/libarchive-3.2.2 (1).tar.gz
$ ls -al Downloads/libarchive-3.2.2\ \(1\).tar.gz 
-rw-r--r-- 1 xxx xxx 5458241 Sep 25 11:07 Downloads/libarchive-3.2.2 (1).tar.gz
$ wget http://libarchive.org/downloads/libarchive-3.2.2.tar.gz
--2018-09-25 11:08:20--  http://libarchive.org/downloads/libarchive-3.2.2.tar.gz
Resolving libarchive.org (libarchive.org)... 143.204.214.25, 143.204.214.15, 143.204.214.129, ...
Connecting to libarchive.org (libarchive.org)|143.204.214.25|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5458241 (5,2M) [application/x-gzip]
Saving to: ‘libarchive-3.2.2.tar.gz’

libarchive-3.2.2.tar.gz               100%[=======================================================================>]   5,21M  10,1MB/s    in 0,5s    

2018-09-25 11:08:20 (10,1 MB/s) - ‘libarchive-3.2.2.tar.gz’ saved [5458241/5458241]

$ ls -al libarchive-3.2.2.tar.gz 
-rw-r--r-- 1 xxx xxx 5458241 2016-10-24 05:44:34 libarchive-3.2.2.tar.gz
$ md5sum libarchive-3.2.2.tar.gz 
1ec00b7dcaf969dd2a5712f85f23c764  libarchive-3.2.2.tar.gz
```
Well we **not** being your IT department, a few hints as a PC user to a PC user (i.e. basics): A good first step, would be to do what I mentioned before and to run a check on your filesystem(s), then another one is to check if your RAM being defective (memtest86).

This has nothing to do with Yocto and even less with our BSP and therefore this issue is **closed**.
